version: '3'

volumes:
    nwvol111:

networks:
    nwnet111:

services:
    nwdb111:
        image: lhuasheng/nwdb111
        build:
            context: ./database
        environment:
        - MYSQL_ROOT_PASSWORD=changeit
        networks:
        - nwnet111
        volumes:
        - nwvol111:/var/lib/mysql

    nwapp111:
        image: lhuasheng/nwapp111
        build:
            context: ./server
        environment:
        - DB_HOST=nwdb111
        - DB_PORT=3306
        - DB_USER=root
        - DB_PASSWORD=changeit
        networks:
        - nwnet111
        ports:
        - 80:3000
