---
apiVersion: v1
kind: Namespace
metadata:
    name: myns

---
apiVersion: apps/v1
kind: Deployment
metadata: 
    name: mydb-deploy
    namespace: myns
    labels:
        name: mydb-deploy
        tier: db
        version: "v1"
spec:
    replicas: 1
    selector:
        matchLabels:
            name: mydb-svc
    template:
        metadata:
            name: mydb-svc
            labels:
                name: mydb-svc
        spec:
            containers:
            - name: mydb-svc
              image: stackupiss/northwind-db:v1
              imagePullPolicy: Always
              envFrom: 
                - configMapRef: 
                    name: db-configmap
                - secretRef:
                    name: db-secret
              ports:
                - name: db-http
                  containerPort: 3306
              resources:
                requests:
                  cpu: "50m"
                  memory: "16Mi"
                limits:
                  cpu: "100m"
                  memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
    name: db-httpservice
    namespace: myns
    labels:
        name: db-httpservice

spec:
    type: ClusterIP
    selector: 
        name: mydb-svc
    ports:
    - name: db-http
      port: 3306
      targetPort: db-http

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: db-configmap
    namespace: myns
    labels:
        name: db-configmap
data:
    #APP_ID: c302f50625bf707080c189724808943a
    MYSQL_DATABASE: northwind
---
apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: myns
    labels: 
        name: db-secret
data:
    MYSQL_ROOT_PASSWORD: Y2hhbmdlaXQ=